name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: docker-compose build
        env:
          TAG: ${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/bin/filter@3c0b4f0
        with:
          args: branch master

      - uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker-compose build
        env:
          TAG: ${{ github.sha }}

      - run: docker-compose push
        env:
          TAG: ${{ github.sha }}

      - run: sed -i s/:latest/:$GITHUB_SHA/ $GITHUB_WORKSPACE/config/deployment.yaml

      - uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig save nyc1 -c $HOME/.kube/config

      - uses: docker://bitnami/kubectl
        with:
          args: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yaml
